repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
    -   id: end-of-file-fixer
    -   id: detect-private-key
    -   id: check-docstring-first
    -   id: check-case-conflict
    -   id: check-ast
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
    -   id: python-bandit-vulnerability-check
        entry: bandit
        args: [-lll, --recursive, .]
        language: system
        files: .py$
        name: bandit
-   repo: https://github.com/pypa/pip-audit
    rev: v2.5.3
    hooks:
      -   id: pip-audit
          args: ["-r", "requirements.txt"]

ci:
  # Leave pip-audit to only run locally and not in CI
  # pre-commit.ci does not allow network calls
  skip: [pip-audit]
